name: annotqc
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - pandas>=2.2.3
  - biopython>=1.85
  - bioconda::blast>=2.16.0
  - bioconda::busco>=5.8.3
  - bioconda::aegean>=0.16.0
  - bioconda::bedtools>=2.25.0